---
# tasks file for apigee-opdk-setup-validate

- name: Install Apigee Validate
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-validate install'

- name: Remove all apigee-validate
  become: yes
  file:
    path: '{{ apigee_validate_config_file }}'
    state: absent

- name: Check for admin email
  fail:
    msg: "Admin email must be provided"
  when: opdk_user_email is not defined

- name: Check for admin password
  fail:
    msg: "Admin password must be provided"
  when: opdk_user_pass is not defined

- name: Create apigee-validate.conf file for RMP
  become: true
  template:
    src: apigee-validate-rmp.conf.j2
    dest: '{{ apigee_validate_config_file }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
  when: groups['dc-1-rmp'] is defined

- name: Create apigee-validate.conf file for Router separate from MP
  become: true
  template:
    src: apigee-validate-r-mp.conf.j2
    dest: '{{ apigee_validate_config_file }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
  when: groups['r'] is defined and groups['mp']

#- name: Validate OPDK Installation
#  expect:
#    command: '/opt/apigee/apigee-service/bin/apigee-service apigee-validate setup -f {{ apigee_validate_config_file }}'
#    responses:
#      '(?i)Press a key:': '\n'
#  when: opdk_version | version_compare('4.16.09', '<')

- name: Validate OPDK Installation
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-validate setup -f {{ apigee_validate_config_file }}'

